
package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublicadorProveedor", targetNamespace = "http://Servidor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorProveedor {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ws.DataInfoServicio
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/PublicadorProveedor/verInfoServicioRequest", output = "http://Servidor/PublicadorProveedor/verInfoServicioResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servidor/PublicadorProveedor/verInfoServicio/Fault/Exception")
    })
    public DataInfoServicio verInfoServicio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ws.DataServicio
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/PublicadorProveedor/informacionServicioRequest", output = "http://Servidor/PublicadorProveedor/informacionServicioResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servidor/PublicadorProveedor/informacionServicio/Fault/Exception")
    })
    public DataServicio informacionServicio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ws.DataInfoPromocion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/PublicadorProveedor/verInfoPromocionRequest", output = "http://Servidor/PublicadorProveedor/verInfoPromocionResponse")
    public DataInfoPromocion verInfoPromocion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/vaciarCategoriasServicioRequest", output = "http://Servidor/PublicadorProveedor/vaciarCategoriasServicioResponse")
    public void vaciarCategoriasServicio();

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/ingresarCategoriaServicioRequest", output = "http://Servidor/PublicadorProveedor/ingresarCategoriaServicioResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servidor/PublicadorProveedor/ingresarCategoriaServicio/Fault/Exception")
    })
    public void ingresarCategoriaServicio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/ingresarDestinoServicioRequest", output = "http://Servidor/PublicadorProveedor/ingresarDestinoServicioResponse")
    public void ingresarDestinoServicio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/ingresarImagenServicioRequest", output = "http://Servidor/PublicadorProveedor/ingresarImagenServicioResponse")
    public void ingresarImagenServicio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/altaServicioRequest", output = "http://Servidor/PublicadorProveedor/altaServicioResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servidor/PublicadorProveedor/altaServicio/Fault/Exception")
    })
    public void altaServicio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/ingresarNombreCategoriaRequest", output = "http://Servidor/PublicadorProveedor/ingresarNombreCategoriaResponse")
    public void ingresarNombreCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/seleccionarPadreRequest", output = "http://Servidor/PublicadorProveedor/seleccionarPadreResponse")
    public void seleccionarPadre(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/altaCategoriaRequest", output = "http://Servidor/PublicadorProveedor/altaCategoriaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servidor/PublicadorProveedor/altaCategoria/Fault/Exception")
    })
    public void altaCategoria()
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.DataInfoProveedor
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/PublicadorProveedor/verInfoProveedorRequest", output = "http://Servidor/PublicadorProveedor/verInfoProveedorResponse")
    public DataInfoProveedor verInfoProveedor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/ingresarCategoriaBorrarServicioRequest", output = "http://Servidor/PublicadorProveedor/ingresarCategoriaBorrarServicioResponse")
    public void ingresarCategoriaBorrarServicio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/ingresarDescripcionServicioRequest", output = "http://Servidor/PublicadorProveedor/ingresarDescripcionServicioResponse")
    public void ingresarDescripcionServicio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/seleccionarProveedorRequest", output = "http://Servidor/PublicadorProveedor/seleccionarProveedorResponse")
    public void seleccionarProveedor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/seleccionarServicioRequest", output = "http://Servidor/PublicadorProveedor/seleccionarServicioResponse")
    public void seleccionarServicio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/ingresarOrigenServicioRequest", output = "http://Servidor/PublicadorProveedor/ingresarOrigenServicioResponse")
    public void ingresarOrigenServicio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/ingresarPrecioServicioRequest", output = "http://Servidor/PublicadorProveedor/ingresarPrecioServicioResponse")
    public void ingresarPrecioServicio(
        @WebParam(name = "arg0", partName = "arg0")
        float arg0);

    /**
     * 
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/modificarServicioRequest", output = "http://Servidor/PublicadorProveedor/modificarServicioResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servidor/PublicadorProveedor/modificarServicio/Fault/Exception")
    })
    public void modificarServicio()
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/ingresarImagenBorrarServicioRequest", output = "http://Servidor/PublicadorProveedor/ingresarImagenBorrarServicioResponse")
    public void ingresarImagenBorrarServicio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/ingresarModificarImagenServicioRequest", output = "http://Servidor/PublicadorProveedor/ingresarModificarImagenServicioResponse")
    public void ingresarModificarImagenServicio(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/altaPaisRequest", output = "http://Servidor/PublicadorProveedor/altaPaisResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servidor/PublicadorProveedor/altaPais/Fault/Exception")
    })
    public void altaPais(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/PublicadorProveedor/altaCiudadRequest", output = "http://Servidor/PublicadorProveedor/altaCiudadResponse")
    public void altaCiudad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ws.DataPromocion
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/PublicadorProveedor/informacionPromocionRequest", output = "http://Servidor/PublicadorProveedor/informacionPromocionResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servidor/PublicadorProveedor/informacionPromocion/Fault/Exception")
    })
    public DataPromocion informacionPromocion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws Exception_Exception
    ;

}
