
package wsc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublicadorClienteService", targetNamespace = "http://Servidor/", wsdlLocation = "http://localhost:3000/publicadorCliente?wsdl")
public class PublicadorClienteService
    extends Service
{

    private final static URL PUBLICADORCLIENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORCLIENTESERVICE_EXCEPTION;
    private final static QName PUBLICADORCLIENTESERVICE_QNAME = new QName("http://Servidor/", "PublicadorClienteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3000/publicadorCliente?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORCLIENTESERVICE_WSDL_LOCATION = url;
        PUBLICADORCLIENTESERVICE_EXCEPTION = e;
    }

    public PublicadorClienteService() {
        super(__getWsdlLocation(), PUBLICADORCLIENTESERVICE_QNAME);
    }

    public PublicadorClienteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORCLIENTESERVICE_QNAME, features);
    }

    public PublicadorClienteService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORCLIENTESERVICE_QNAME);
    }

    public PublicadorClienteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORCLIENTESERVICE_QNAME, features);
    }

    public PublicadorClienteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorClienteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorCliente
     */
    @WebEndpoint(name = "PublicadorClientePort")
    public PublicadorCliente getPublicadorClientePort() {
        return super.getPort(new QName("http://Servidor/", "PublicadorClientePort"), PublicadorCliente.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorCliente
     */
    @WebEndpoint(name = "PublicadorClientePort")
    public PublicadorCliente getPublicadorClientePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Servidor/", "PublicadorClientePort"), PublicadorCliente.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORCLIENTESERVICE_EXCEPTION!= null) {
            throw PUBLICADORCLIENTESERVICE_EXCEPTION;
        }
        return PUBLICADORCLIENTESERVICE_WSDL_LOCATION;
    }

}
