/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;
import logica.DataCategoria;
import logica.DataCiudad;
import logica.DataProveedor;
import logica.DataServicio;

/**
 *
 * @author Mati
 */
public class AltaServicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaServicio
     */
    PantallaPrincipal Pantallaprin = PantallaPrincipal.getInstancia();
    public Object seleccionado;
   

    public void armarArbol(DefaultMutableTreeNode raiz, List<DataCategoria> dtps) {
        for (DataCategoria dtcategoria : dtps) {
            DefaultMutableTreeNode cate = new DefaultMutableTreeNode();
            cate.setUserObject(dtcategoria);
            raiz.add(cate);
            armarArbol(cate, dtcategoria.getHijos());
        }
    }

    public void categoriasServicio(){
        Pantallaprin.ICP.vaciarCategoriasServicio();//Vacio las categorias del aterior click
        TreePath[] equis  = jTree1.getSelectionPaths();
        for (TreePath x : equis){
            String padreSelec = x.toString();
            padreSelec = padreSelec.substring(padreSelec.lastIndexOf(",") + 2, padreSelec.lastIndexOf("]"));
            try {
                //JOptionPane.showMessageDialog(null,"El padre seleccionado es "+padreSelec);
                Pantallaprin.ICP.ingresarCategoriaServicio(padreSelec);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        }
    }
    
    public AltaServicio() {
        initComponents();
        //Se agregan todas las categorias al arblol
        int precioin = 0;
        TreeModel jmodel;
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Categorías");
        List<DataCategoria> dtps = Pantallaprin.ICP.listarCategorias();
        armarArbol(raiz, dtps);
        DefaultTreeModel modeloArbol = new DefaultTreeModel(raiz);
        jTree1.setModel(modeloArbol);
        //Se agregan todos los proveedores en el conbobox
        List<DataProveedor> p = Pantallaprin.ICP.listarProveedores();
        Iterator<DataProveedor> it = p.iterator();
        while (it.hasNext()) {
            DataProveedor dts = it.next();
            String n = dts.getNickname();
            proveedores.addItem(n);
        }
        //Se agregan todos los paies en el conbobox
        Set<String> paises = Pantallaprin.ICP.infoPaises();
        Iterator<String> it2 = paises.iterator();
        while (it2.hasNext()) {
            String dts = it2.next();
            paisesorigen.addItem (dts);
            paiesesdestino.addItem(dts);
        }
        jTree1.setSelectionRow(0); //Selecciono la raiz
        nombre.requestFocus();
    }
    
    public static boolean esNumerico(String str){
        return str.matches("\\d+(\\.\\d+)?");  //matchea numeros con decimales
    }
    
    public String letraCapital(String texto){
    //Convierte la primera letra de una texto a mayuscula, el resto a minusculas
        String resultado = "";
        if(!texto.isEmpty()){
            texto = texto.toLowerCase(); //pasamos a minuscula
            String[] palabras = texto.split("\\s"); //partimos si tiene mas de una palabra
            for(String palabra : palabras) {
                resultado += palabra.substring(0, 1).toUpperCase() + palabra.substring(1)+ " ";
            }
        }
        return resultado;
    }
        
    public void limpiarCampos(){
        nombre.setText("");
        descripcion.setText("");
        servicioImagen1.setText("");
        servicioImagen2.setText("");
        servicioImagen3.setText("");
        precio.setText("");
        
        jTree1.setSelectionRow(0); //Selecciono la raiz
        nombre.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     * @return
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        proveedores = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        servicioImagen1 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        servicioImagen2 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        servicioImagen3 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        paisesorigen = new javax.swing.JComboBox();
        paiesesdestino = new javax.swing.JComboBox();
        ciundadDestino = new javax.swing.JComboBox();
        ciudadaOrigen = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Nuevo servicio");
        setFrameIcon(new javax.swing.ImageIcon("/ens/home01/r/rodrigo.linares/NetBeansProjects/tpgr07/TallerJava/src/Imagenes/iconoH4T.png")); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setText("Servicio");

        jLabel24.setText("Nombre:");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel25.setText("Proveedor:");

        proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoresActionPerformed(evt);
            }
        });

        jLabel26.setText("Descripción:");

        jLabel27.setText("Imagen:");

        jButton13.setText("...");
        jButton13.setInheritsPopupMenu(true);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel28.setText("Precio:");

        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });
        precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precioKeyPressed(evt);
            }
        });

        jLabel29.setText("Ciudad origen:");

        jLabel30.setText("Ciudad destino:");

        jLabel31.setText("Categorias:");

        jButton14.setText("Aceptar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Cancelar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        descripcion.setColumns(20);
        descripcion.setLineWrap(true);
        descripcion.setRows(5);
        jScrollPane2.setViewportView(descripcion);

        jButton16.setText("...");
        jButton16.setInheritsPopupMenu(true);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("...");
        jButton17.setInheritsPopupMenu(true);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel32.setText("Pais:");

        jLabel33.setText("Pais:");

        paisesorigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paisesorigenMouseClicked(evt);
            }
        });
        paisesorigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisesorigenActionPerformed(evt);
            }
        });

        paiesesdestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        paiesesdestino.setToolTipText("");
        paiesesdestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paiesesdestinoActionPerformed(evt);
            }
        });

        ciundadDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        ciundadDestino.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26)
                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel28)
                            .addComponent(jLabel32)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(servicioImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(servicioImagen3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(servicioImagen2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ciudadaOrigen, 0, 176, Short.MAX_VALUE)
                                    .addComponent(paisesorigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(paiesesdestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ciundadDestino, 0, 179, Short.MAX_VALUE)))
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton14)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton15))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel25)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel31)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabel27)
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paisesorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paiesesdestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29)
                                .addComponent(ciudadaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ciundadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton15)
                                    .addComponent(jButton14))
                                .addGap(16, 16, 16))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(servicioImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(servicioImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(servicioImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton17))
                        .addGap(166, 166, 166)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteNickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteNickActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        //Pantallaprin.ICP.altaProveedor(proveedorNick.getText() ,proveedorNombre.getText(), proveedorApellido.getText(), proveedorEmail.getText() ,selectedDate , proveedorImagen.getText(), proveedorEmpresaNombre.getText(),proveedorEmpresaLink.getText());
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void clienteNick1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteNick1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteNick1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        //Pantallaprin.ICP.altaProveedor(proveedorNick.getText() ,proveedorNombre.getText(), proveedorApellido.getText(), proveedorEmail.getText() ,selectedDate , proveedorImagen.getText(), proveedorEmpresaNombre.getText(),proveedorEmpresaLink.getText());
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void clienteNick2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteNick2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteNick2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
          this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nombreActionPerformed

    private void proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedoresActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        Pantallaprin.abrirSelectorImagen("AltaServicio1");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        
        if(proveedores.getItemCount() < 1){
            JOptionPane.showMessageDialog(null, "No hay proveedores ingresados al sistema");
            return;
        }   
        if(!esNumerico(precio.getText())){
            JOptionPane.showMessageDialog(null, "Ingrese un precio válido");
            precio.requestFocus();
            return;
        }        
        try{
            categoriasServicio(); //chequeo que los servicios seleccionados sean hojas        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        }
        
        String nombreServicio  = letraCapital(nombre.getText());
        String descServicio    = descripcion.getText();
        String proveedor       = proveedores.getSelectedItem().toString();
        String ciudadOrigen    = letraCapital(ciudadaOrigen.getSelectedItem().toString());
        String ciudadDestino   = letraCapital(ciundadDestino.getSelectedItem().toString());
        String paisServicio    = letraCapital(paisesorigen.getSelectedItem().toString());
        int precioServicio     = Integer.parseInt(precio.getText());            
        
        if(nombreServicio.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un nombre válido");
            nombre.requestFocus();
            return;
        }
        else if(descServicio.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese una descripción válida");
            descripcion.requestFocus();
            return;
        }
    
        else if(precioServicio <= 0){
            JOptionPane.showMessageDialog(null, "Ingrese un precio válido.");
            precio.requestFocus();
            return;
        }        
        
        try{
                Pantallaprin.ICP.ingresarDestinoServicio(ciudadDestino);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());            
        }                
        
        if (!servicioImagen1.getText().isEmpty()) {
            Path FROM = Paths.get(servicioImagen1.getText());
            //armo la ruta destino
            String urlImagenDestino = PantallaPrincipal.RutaImagenes + "Servicios/" + proveedor + " - " + nombre.getText() + " 1.png";
            Path TO = Paths.get(urlImagenDestino);
            try {
                Files.copy(FROM, TO, StandardCopyOption.REPLACE_EXISTING);
                Pantallaprin.ICP.ingresarImagenServicio(urlImagenDestino);//luego del alta el servicio deve quedar en memoria
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al copiar la imagen 1");
                Logger.getLogger(SelectorImagen.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Pantallaprin.ICP.ingresarImagenServicio("");//siempre se carga una ruta aunque sea vacia
        }
        if (!servicioImagen2.getText().isEmpty()) {
            Path FROM = Paths.get(servicioImagen2.getText());
            //armo la ruta destino
            String urlImagenDestino = PantallaPrincipal.RutaImagenes + "Servicios/" + proveedor + " - " + nombre.getText() + " 2.png";
            Path TO = Paths.get(urlImagenDestino);
            try {
                Files.copy(FROM, TO, StandardCopyOption.REPLACE_EXISTING);
                Pantallaprin.ICP.ingresarImagenServicio(urlImagenDestino);//luego del alta el servicio deve quedar en memoria
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al copiar la imagen 2");
                Logger.getLogger(SelectorImagen.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Pantallaprin.ICP.ingresarImagenServicio("");//siempre se carga una ruta aun que sea vacia
        }
        if (!servicioImagen3.getText().isEmpty()) {
            Path FROM = Paths.get(servicioImagen3.getText());
            //armo la ruta destino
            String urlImagenDestino = PantallaPrincipal.RutaImagenes + "Servicios/" + proveedor + " - " + nombre.getText() + " 3.png";
            Path TO = Paths.get(urlImagenDestino);
            try {
                Files.copy(FROM, TO, StandardCopyOption.REPLACE_EXISTING);
                Pantallaprin.ICP.ingresarImagenServicio(urlImagenDestino);//luego del alta el servicio deve quedar en memoria
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error al copiar la imagen 3");
                Logger.getLogger(SelectorImagen.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Pantallaprin.ICP.ingresarImagenServicio("");//siempre se carga una ruta aun que sea vacia
        }
        try {          
            Pantallaprin.ICP.altaServicio(nombreServicio, descServicio, precioServicio, ciudadOrigen, proveedor, paisServicio);
            JOptionPane.showMessageDialog(null, "El Servicio se ingresó correctamente");
            limpiarCampos();
        } catch (Exception ex) {
            //error en alta servicio
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        Pantallaprin.abrirSelectorImagen("AltaServicio2");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        Pantallaprin.abrirSelectorImagen("AltaServicio3");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        Pantallaprin.ICP.vaciarCategoriasServicio();//Vacio las categorias del aterior click
        TreePath[] equis  = jTree1.getSelectionPaths();
        for (TreePath x : equis){
            String padreSelec = x.toString();
            padreSelec = padreSelec.substring(padreSelec.lastIndexOf(",") + 2, padreSelec.lastIndexOf("]"));
            try {
                //JOptionPane.showMessageDialog(null,"El padre seleccionado es "+padreSelec);
                Pantallaprin.ICP.ingresarCategoriaServicio(padreSelec);
            } catch (Exception ex) {
               // JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        }
    }//GEN-LAST:event_jTree1MouseClicked

    private void precioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioKeyPressed

    private void paisesorigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paisesorigenMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_paisesorigenMouseClicked

    private void paisesorigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisesorigenActionPerformed
        // TODO add your handling code here:
        ciudadaOrigen.removeAllItems();
         List<DataCiudad> dat = Pantallaprin.ICP.ciudadesXpais(paisesorigen.getSelectedItem().toString());
        //JOptionPane.showMessageDialog(null,paisesorigen.getSelectedItem().toString());
        for (DataCiudad d : dat ){
            
            ciudadaOrigen.addItem(d.getNombre());
        }
    }//GEN-LAST:event_paisesorigenActionPerformed

    private void paiesesdestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paiesesdestinoActionPerformed
        // TODO add your handling code here:
         ciundadDestino.removeAllItems();
          ciundadDestino.addItem("");
         List<DataCiudad> dat = Pantallaprin.ICP.ciudadesXpais(paiesesdestino.getSelectedItem().toString());
        //JOptionPane.showMessageDialog(null,paisesorigen.getSelectedItem().toString());
        for (DataCiudad d : dat ){
            
            ciundadDestino.addItem(d.getNombre());
        }
    }//GEN-LAST:event_paiesesdestinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ciudadaOrigen;
    private javax.swing.JComboBox ciundadDestino;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    public static javax.swing.JTextField nombre;
    private javax.swing.JComboBox paiesesdestino;
    private javax.swing.JComboBox paisesorigen;
    public static javax.swing.JTextField precio;
    private javax.swing.JComboBox proveedores;
    public static javax.swing.JTextField servicioImagen1;
    public static javax.swing.JTextField servicioImagen2;
    public static javax.swing.JTextField servicioImagen3;
    // End of variables declaration//GEN-END:variables
}
